# Generated by Django 5.2.5 on 2025-12-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=120, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "administrator",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
