# Generated by Django 5.2.5 on 2025-12-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0002_administrator_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryMas",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("shortname", models.CharField(max_length=20, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CountryMas",
            },
        ),
    ]
