# Generated by Django 5.2.5 on 2025-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0003_countrymas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countrymas",
            old_name="user_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="countrymas",
            name="admin_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
