# Generated by Django 5.2.5 on 2025-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0004_rename_user_id_countrymas_id_countrymas_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
