# Generated by Django 5.2.5 on 2025-12-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0006_statemas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statemas",
            name="country_id",
        ),
        migrations.AddField(
            model_name="statemas",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="states",
                to="textile.countrymas",
            ),
        ),
    ]
