# Generated by Django 5.2.5 on 2025-12-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0007_remove_statemas_country_id_statemas_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statemas",
            name="country",
        ),
        migrations.AddField(
            model_name="statemas",
            name="country_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
