# Generated by Django 5.2.5 on 2025-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0008_remove_statemas_country_statemas_country_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("shortname", models.CharField(max_length=20, unique=True)),
                ("state_id", models.IntegerField(blank=True, null=True)),
                ("country_id", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CityMas",
            },
        ),
    ]
