# Generated by Django 5.2.5 on 2025-12-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0009_citymas"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeMas",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("createddatetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "GradeMas",
            },
        ),
    ]
