# Generated by Django 5.2.5 on 2025-12-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0010_grademas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grademas",
            old_name="createddatetime",
            new_name="created_at",
        ),
    ]
