# Generated by Django 5.2.5 on 2025-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0012_groupmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleMas",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("shortname", models.CharField(max_length=25)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "TitleMas",
            },
        ),
    ]
