# Generated by Django 5.2.5 on 2025-12-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0013_titlemas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlemas",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="titlemas",
            name="shortname",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
