# Generated by Django 5.2.5 on 2025-12-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0014_alter_titlemas_name_alter_titlemas_shortname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grademas",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="groupmas",
            old_name="code",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="titlemas",
            old_name="code",
            new_name="id",
        ),
    ]
