# Generated by Django 5.2.5 on 2025-12-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0016_categorymas"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReligionMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ReligionMas",
            },
        ),
    ]
