# Generated by Django 5.2.5 on 2025-12-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0019_occupationmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                (
                    "cardservicecharge",
                    models.DecimalField(decimal_places=3, max_digits=18),
                ),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("altered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "BankMas",
            },
        ),
    ]
