# Generated by Django 5.2.5 on 2025-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0020_bankmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starname", models.CharField(max_length=10, unique=True)),
                ("starvalue", models.DecimalField(decimal_places=2, max_digits=9)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "StarMas",
            },
        ),
    ]
