# Generated by Django 5.2.5 on 2025-12-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0021_starmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("shortname", models.CharField(blank=True, max_length=25, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("createddatetime", models.DateTimeField(auto_now_add=True)),
                (
                    "perdaycommission",
                    models.DecimalField(decimal_places=5, max_digits=18),
                ),
            ],
            options={
                "db_table": "DepartmentMas",
            },
        ),
    ]
