# Generated by Django 5.2.5 on 2025-12-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0022_departmentmas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departmentmas",
            old_name="createddatetime",
            new_name="created_at",
        ),
    ]
