# Generated by Django 5.2.5 on 2025-12-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0023_rename_createddatetime_departmentmas_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="titlemas",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
