# Generated by Django 5.2.5 on 2025-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0024_rename_create_at_titlemas_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferModeMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("shortname", models.CharField(blank=True, max_length=25, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("numgeneration", models.BooleanField()),
            ],
            options={
                "db_table": "TransferModeMas",
            },
        ),
    ]
