# Generated by Django 5.2.5 on 2025-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0025_transfermodemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftvoucherMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=35, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "GiftvoucherMas",
            },
        ),
    ]
