# Generated by Django 5.2.5 on 2025-12-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0027_paymentmodemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discounttypemas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("discper", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                "db_table": "DiscountTypeMas",
            },
        ),
    ]
