# Generated by Django 5.2.5 on 2025-12-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0028_discounttypemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("citycode", models.IntegerField(blank=True, null=True)),
                ("phoneno", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.CharField(blank=True, max_length=50, null=True)),
                ("tinno", models.CharField(blank=True, max_length=50, null=True)),
                ("tindate", models.DateTimeField(blank=True, null=True)),
                ("areacode", models.CharField(blank=True, max_length=50, null=True)),
                ("cstno", models.CharField(blank=True, max_length=50, null=True)),
                ("cstdate", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=50, null=True)),
                ("servername", models.CharField(blank=True, max_length=50, null=True)),
                ("serveruid", models.CharField(blank=True, max_length=25, null=True)),
                ("dbname", models.CharField(blank=True, max_length=50, null=True)),
                ("serverpwd", models.CharField(blank=True, max_length=25, null=True)),
                ("servermode", models.CharField(blank=True, max_length=25, null=True)),
                ("protocol", models.CharField(blank=True, max_length=25, null=True)),
                ("mainserver", models.BooleanField(default=False)),
                ("accdbname", models.CharField(blank=True, max_length=50, null=True)),
                ("ipaddress", models.CharField(blank=True, max_length=25, null=True)),
                ("uploaddata", models.BooleanField(default=False)),
            ],
        ),
    ]
