# Generated by Django 5.2.5 on 2025-12-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0029_locationmas"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="locationmas",
            table="LocationMas",
        ),
    ]
