# Generated by Django 5.2.5 on 2025-12-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0030_alter_locationmas_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterMas",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("counter_group_code", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("section_code", models.IntegerField(blank=True, null=True)),
                ("counter_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "CounterMas",
                "managed": False,
            },
        ),
    ]
