# Generated by Django 5.2.5 on 2025-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0031_countermas"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMas",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("macid", models.CharField(blank=True, max_length=50, null=True)),
                ("print_function_code", models.IntegerField(blank=True, null=True)),
                (
                    "group_bill_prefix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("seperator", models.CharField(blank=True, max_length=5, null=True)),
                ("no_length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_no", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("floor_code", models.IntegerField(blank=True, null=True)),
                (
                    "return_system",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "settlement_print_function_code",
                    models.IntegerField(blank=True, null=True),
                ),
                ("sys_ref_no", models.CharField(blank=True, max_length=50, null=True)),
                ("allow_scheme", models.BooleanField(blank=True, null=True)),
                ("printer_port_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "SystemMas",
                "managed": False,
            },
        ),
    ]
