# Generated by Django 5.2.5 on 2025-12-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0033_taxtypemas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CounterMas",
        ),
        migrations.DeleteModel(
            name="SystemMas",
        ),
        migrations.DeleteModel(
            name="TaxTypeMas",
        ),
    ]
