# Generated by Django 5.2.5 on 2025-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0034_delete_countermas_delete_systemmas_delete_taxtypemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("counter_group_code", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("section_code", models.IntegerField(blank=True, null=True)),
                ("counter_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "CounterMas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SystemMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("macid", models.CharField(blank=True, max_length=50, null=True)),
                ("print_function_code", models.IntegerField(blank=True, null=True)),
                (
                    "group_bill_prefix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("seperator", models.CharField(blank=True, max_length=5, null=True)),
                ("no_length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_no", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("floor_code", models.IntegerField(blank=True, null=True)),
                (
                    "return_system",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "settlement_print_function_code",
                    models.IntegerField(blank=True, null=True),
                ),
                ("sys_ref_no", models.CharField(blank=True, max_length=50, null=True)),
                ("allow_scheme", models.BooleanField(blank=True, null=True)),
                ("printer_port_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "SystemMas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TaxTypeMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entry_type", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("tax_percent", models.DecimalField(decimal_places=5, max_digits=10)),
                ("tax_on", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("include", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("is_discount", models.BooleanField(default=False)),
                ("allow_sales", models.BooleanField(default=False)),
                ("allow_purchase", models.BooleanField(default=False)),
                (
                    "acc_head_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_post", models.BooleanField(default=False)),
                ("account_head_code", models.IntegerField(blank=True, null=True)),
                ("account_sales_head_code", models.IntegerField(blank=True, null=True)),
                ("ss_pur_acc_head_code", models.IntegerField(blank=True, null=True)),
                ("ss_sal_acc_head_code", models.IntegerField(blank=True, null=True)),
                (
                    "tax_amt_cal_type",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("allow_tax_amt_cal", models.BooleanField(default=False)),
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "local_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "other_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "import_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "TaxTypeMas",
                "managed": False,
            },
        ),
    ]
