# Generated by Django 5.2.5 on 2025-12-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0035_countermas_systemmas_taxtypemas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationmas",
            old_name="areacode",
            new_name="areaid",
        ),
        migrations.RenameField(
            model_name="locationmas",
            old_name="citycode",
            new_name="cityid",
        ),
        migrations.RenameField(
            model_name="locationmas",
            old_name="pincode",
            new_name="pinid",
        ),
    ]
