# Generated by Django 5.2.5 on 2025-12-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0036_rename_areacode_locationmas_areaid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterGroupMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "CounterGroupMas",
            },
        ),
        migrations.DeleteModel(
            name="CounterMas",
        ),
        migrations.DeleteModel(
            name="SystemMas",
        ),
        migrations.DeleteModel(
            name="TaxTypeMas",
        ),
    ]
