# Generated by Django 5.2.5 on 2025-12-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0037_countergroupmas_delete_countermas_delete_systemmas_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countergroupmas",
            old_name="created_datetime",
            new_name="created_at",
        ),
    ]
