# Generated by Django 5.2.5 on 2025-12-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0038_rename_created_datetime_countergroupmas_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupHeadMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("group_head_code", models.IntegerField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("type", models.CharField(blank=True, max_length=1, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "GroupHeadMas",
            },
        ),
    ]
