# Generated by Django 5.2.5 on 2025-12-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0039_groupheadmas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationmas",
            old_name="cityid",
            new_name="city_id",
        ),
    ]
