# Generated by Django 5.2.5 on 2025-12-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0040_rename_cityid_locationmas_city_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHeadMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("head_type", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("group_head_code", models.IntegerField(blank=True, null=True)),
                (
                    "classification_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("accessible_value", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "AccountHeadMas",
            },
        ),
    ]
