# Generated by Django 5.2.5 on 2025-12-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0041_accountheadmas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountheadmas",
            old_name="group_head_code",
            new_name="group_head_id",
        ),
    ]
