# Generated by Django 5.2.5 on 2025-12-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0042_rename_group_head_code_accountheadmas_group_head_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeAndExpenseMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("head_type", models.BooleanField(default=False)),
                (
                    "account_head_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_post", models.BooleanField(default=False)),
                ("account_head_code", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "IncomeAndExpenseMas",
            },
        ),
    ]
