# Generated by Django 5.2.5 on 2025-12-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0044_countermas"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("short_name", models.CharField(blank=True, max_length=25, null=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "FloorMas",
            },
        ),
    ]
