# Generated by Django 5.2.5 on 2025-12-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0045_floormas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="floormas",
            old_name="location_code",
            new_name="location_id",
        ),
    ]
