# Generated by Django 5.2.5 on 2025-12-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0047_taxtypemas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxtypemas",
            options={},
        ),
    ]
