# Generated by Django 5.2.5 on 2025-12-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0048_alter_taxtypemas_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxtypemas",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[("ADD / LESS", "ADD / LESS"), ("TAX TYPE", "TAX TYPE")],
                max_length=10,
                null=True,
            ),
        ),
    ]
