# Generated by Django 5.2.5 on 2025-12-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0049_alter_taxtypemas_entry_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxtypemas",
            options={"managed": True},
        ),
    ]
