# Generated by Django 5.2.5 on 2025-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0050_alter_taxtypemas_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("mac_id", models.CharField(blank=True, max_length=50, null=True)),
                ("print_function_code", models.IntegerField(blank=True, null=True)),
                (
                    "group_bill_prefix",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("seperator", models.CharField(blank=True, max_length=5, null=True)),
                ("no_length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_no", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("floor_id", models.IntegerField(blank=True, null=True)),
                (
                    "return_system",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "settlement_print_function_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("sys_ref_no", models.CharField(blank=True, max_length=50, null=True)),
                ("allow_scheme", models.BooleanField(default=False)),
                ("printer_port_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "SystemMas",
            },
        ),
        migrations.DeleteModel(
            name="TaxTypeMas",
        ),
    ]
