# Generated by Django 5.2.5 on 2025-12-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0052_taxtypemas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemMas",
        ),
        migrations.DeleteModel(
            name="TaxTypeMas",
        ),
    ]
