# Generated by Django 5.2.5 on 2025-12-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0055_systemmas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemCounterIntegrationMas",
        ),
    ]
