# Generated by Django 5.2.5 on 2025-12-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0056_delete_systemcounterintegrationmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemCounterIntegrationMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("counter_id", models.IntegerField(blank=True, null=True)),
                ("system_type", models.CharField(max_length=25)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("location_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "SystemCounterIntegrationMas",
            },
        ),
    ]
