# Generated by Django 5.2.5 on 2025-12-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0057_systemcounterintegrationmas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemcounterintegrationmas",
            old_name="system_type",
            new_name="system_id",
        ),
        migrations.RenameField(
            model_name="systemmas",
            old_name="created_datetime",
            new_name="created_at",
        ),
    ]
