# Generated by Django 5.2.5 on 2025-12-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "textile",
            "0058_rename_system_type_systemcounterintegrationmas_system_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmas",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systemmas",
            name="allow_scheme",
            field=models.BooleanField(default=False),
        ),
    ]
