# Generated by Django 5.2.5 on 2025-12-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0059_alter_systemmas_active_alter_systemmas_allow_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmas",
            name="seperator",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
