# Generated by Django 5.2.5 on 2025-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0060_alter_systemmas_seperator"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxTypeMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "entry_type",
                    models.CharField(
                        blank=True,
                        choices=[("TAX_TYPE", "Tax Type"), ("ADD_LESS", "ADD/LESS")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=25)),
                ("tax_percent", models.DecimalField(decimal_places=5, max_digits=10)),
                ("tax_on", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("include", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("is_discount", models.BooleanField(default=False)),
                ("allow_sales", models.BooleanField(default=False)),
                ("allow_purchase", models.BooleanField(default=False)),
                (
                    "acc_head_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_post", models.BooleanField(default=False)),
                ("account_head_code", models.IntegerField(blank=True, null=True)),
                ("account_sales_head_code", models.IntegerField(blank=True, null=True)),
                ("ss_pur_acc_head_code", models.IntegerField(blank=True, null=True)),
                ("ss_sal_acc_head_code", models.IntegerField(blank=True, null=True)),
                (
                    "tax_amt_cal_type",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("allow_tax_amt_cal", models.BooleanField(default=False)),
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("section", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "local_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "other_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "import_category",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "TaxTypeMas",
            },
        ),
    ]
