# Generated by Django 5.2.5 on 2025-12-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0061_taxtypemas"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaxTypeMas",
        ),
    ]
