# Generated by Django 5.2.5 on 2025-12-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0064_employeemas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeemas",
            options={"managed": True},
        ),
    ]
