# Generated by Django 5.2.5 on 2025-12-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0065_alter_employeemas_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeMas",
        ),
    ]
