# Generated by Django 5.2.5 on 2025-12-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0066_delete_employeemas"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeMas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_code", models.IntegerField(default=0)),
                ("title_code", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(default="", max_length=25)),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("city_code", models.IntegerField(default=0)),
                ("pincode", models.CharField(blank=True, max_length=50, null=True)),
                ("dob", models.DateTimeField(blank=True, null=True)),
                ("doj", models.DateTimeField(blank=True, null=True)),
                ("dol", models.DateTimeField(blank=True, null=True)),
                ("phoneno", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.CharField(blank=True, max_length=50, null=True)),
                ("panno", models.CharField(blank=True, max_length=50, null=True)),
                ("commission_allowed", models.BooleanField(default=False)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                ("salesman_incentive", models.BooleanField(default=False)),
                ("incentive_qty_based", models.BooleanField(default=False)),
                (
                    "incentive_percentage",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "incentive_amount",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
                ("login_user", models.BooleanField(default=False)),
                ("user_group_code", models.IntegerField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                ("editing_no_of_days", models.IntegerField(default=0)),
                ("profit_from_cost", models.BooleanField(default=False)),
                ("access_time_from", models.DateTimeField(blank=True, null=True)),
                ("access_time_to", models.DateTimeField(blank=True, null=True)),
                ("system_restrict", models.BooleanField(default=False)),
                ("sales_less_cost_in_pur", models.BooleanField(default=False)),
                ("sales_less_cost_in_sales", models.BooleanField(default=False)),
                ("old_bill_cancel", models.BooleanField(default=False)),
                (
                    "default_page",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("desc_edit", models.BooleanField(default=False)),
                ("change_emp_rights", models.BooleanField(default=False)),
                ("allow_sales_discount", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("skin_name", models.CharField(default="Default", max_length=25)),
                ("admin_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("department_code", models.IntegerField(default=0)),
                ("allow_change_location", models.BooleanField(default=False)),
                ("allow_view_actual_sales", models.BooleanField(default=False)),
                ("floor_code", models.IntegerField(default=0)),
                ("allow_lock_date", models.BooleanField(default=False)),
                ("stock_verification", models.BooleanField(default=False)),
                ("report_column_change", models.BooleanField(default=False)),
                ("day_based_incentive", models.BooleanField(default=False)),
                (
                    "day_based_incentive_amount",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
                ("allow_all_user", models.BooleanField(default=False)),
                ("print_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "max_advance",
                    models.DecimalField(decimal_places=5, default=0, max_digits=12),
                ),
                ("allow_view_cost", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("allow_multi_systems", models.BooleanField(default=False)),
                ("no_of_systems", models.IntegerField(default=1)),
                ("display_company_form", models.BooleanField(default=False)),
                (
                    "target_amount",
                    models.DecimalField(decimal_places=5, default=0, max_digits=18),
                ),
            ],
            options={
                "db_table": "EmployeeMas",
                "managed": True,
            },
        ),
    ]
