# Generated by Django 5.2.5 on 2025-12-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0067_employeemas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeemas",
            name="admin_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeemas",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
