# Generated by Django 5.2.5 on 2025-12-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textile", "0068_alter_employeemas_admin_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategoryMas1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas1",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas10",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas10",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas2",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas2",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas3",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas4",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas4",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas5",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas5",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas6",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas6",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas7",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas7",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas8",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas8",
            },
        ),
        migrations.CreateModel(
            name="ItemCategoryMas9",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("shortname", models.CharField(max_length=25, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ItemCategoryMas9",
            },
        ),
    ]
