# Generated by Django 5.2.8 on 2025-12-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textile', '0069_itemcategorymas1_itemcategorymas10_itemcategorymas2_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcategorymas1',
            table='Brand',
        ),
    ]
