# Generated by Django 5.2.8 on 2025-12-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textile', '0070_alter_itemcategorymas1_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcategorymas10',
            table='Size Order',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas2',
            table='Type',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas3',
            table='Style',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas4',
            table='Pattern',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas5',
            table='Color',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas6',
            table='Hsn Code',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas7',
            table='Floor',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas8',
            table='Section',
        ),
        migrations.AlterModelTable(
            name='itemcategorymas9',
            table='Section Group',
        ),
    ]
