# Generated by Django 5.2.8 on 2026-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile', '0071_alter_itemcategorymas10_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemas',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
