# Generated by Django 5.2.8 on 2026-01-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textile', '0072_titlemas_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlemas',
            name='email',
        ),
    ]
