# Generated by Django 5.2.8 on 2025-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.TextField(),
        ),
    ]
