# Generated by Django 5.2.8 on 2025-11-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_adminlogin_password_state_city_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
    ]
