# Generated by Django 5.2.8 on 2025-11-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
