# Generated by Django 5.2.8 on 2025-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_itemcategorymass1_itemcategorymass2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategorymass1',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass2',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass3',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass4',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass5',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass6',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass7',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass8',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemcategorymass9',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
