# Generated by Django 5.2.8 on 2025-11-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_itemcategorymass1_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
