# Generated by Django 5.2.8 on 2025-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_state_city_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
