# Generated by Django 5.2.8 on 2025-11-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_city_id_alter_country_id_alter_state_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
