# Generated by Django 5.2.8 on 2025-11-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_delete_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMas',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('ShortName', models.CharField(max_length=25)),
                ('Active', models.BooleanField(default=True)),
                ('UserID', models.IntegerField()),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CountryMas',
            },
        ),
        migrations.CreateModel(
            name='TitleMas',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('ShortName', models.CharField(max_length=25)),
                ('Active', models.BooleanField(default=True)),
                ('UserID', models.IntegerField()),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TitleMas',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.CreateModel(
            name='StateMas',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('ShortName', models.CharField(max_length=25)),
                ('Active', models.BooleanField(default=True)),
                ('UserID', models.IntegerField()),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('CountryCode', models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.CASCADE, to='shop.countrymas')),
            ],
            options={
                'db_table': 'StateMas',
            },
        ),
        migrations.CreateModel(
            name='CityMas',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('ShortName', models.CharField(max_length=25)),
                ('Active', models.BooleanField(default=True)),
                ('UserID', models.IntegerField()),
                ('CreatedDateTime', models.DateTimeField(auto_now_add=True)),
                ('StateCode', models.ForeignKey(db_column='StateCode', on_delete=django.db.models.deletion.CASCADE, to='shop.statemas')),
            ],
            options={
                'db_table': 'CityMas',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
