# Generated by Django 5.2.8 on 2025-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_accountheadmas_companymas_couriertypemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='citymas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='countrymas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='grademas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='relationmas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='religionmas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='statemas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='titlemas',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
