# Generated by Django 5.2.8 on 2025-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_categorymas_name_alter_citymas_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanksMas',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Shortname', models.CharField(max_length=25)),
                ('CardServiceCharge', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Active', models.BooleanField(default=True)),
                ('UserID', models.IntegerField()),
                ('CreatedDateTime', models.DateTimeField()),
                ('AlterdDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bankmas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='bankmas',
            table='BankMas',
        ),
    ]
