# Generated by Django 5.2.8 on 2025-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_banksmas_alter_bankmas_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmas',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
