# Generated by Django 5.2.8 on 2025-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_departmentmas_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
