# Generated by Django 5.2.8 on 2025-11-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_departmentmas_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtypemas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
