# Generated by Django 5.2.8 on 2025-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_taxtypemas_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countergroupmas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
