# Generated by Django 5.2.8 on 2025-11-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_countergroupmas_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcountermas',
            name='UserEntryDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
