# Generated by Django 5.2.8 on 2025-11-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_systemcountermas_userentrydatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttypemas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='giftvouchermas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
