# Generated by Django 5.2.8 on 2025-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_discounttypemas_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeandexpensemas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfermodemas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
