# Generated by Django 5.2.8 on 2025-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_incomeandexpensemas_createddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
