# Generated by Django 5.2.8 on 2025-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_locationmas_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormas',
            name='CreatedDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
