# Generated by Django 5.2.8 on 2025-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_floormas_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemas',
            name='CommissionPercent',
            field=models.DecimalField(decimal_places=5, default=True, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='DayBasedIncentiveAmount',
            field=models.DecimalField(decimal_places=5, default=True, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='MaxAdvance',
            field=models.DecimalField(decimal_places=5, default=True, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='NoofSystems',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='TargetAmount',
            field=models.DecimalField(decimal_places=5, default=True, max_digits=18, null=True),
        ),
    ]
