# Generated by Django 5.2.8 on 2025-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_employeemas_commissionpercent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermas',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
