# Generated by Django 5.2.8 on 2025-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_suppliermas_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemas',
            name='CountryCode',
            field=models.IntegerField(),
        ),
    ]
