# Generated by Django 5.2.8 on 2025-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_statemas_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymas',
            name='StateCode',
            field=models.IntegerField(),
        ),
    ]
