# Generated by Django 5.2.8 on 2025-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_citymas_statecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationmas',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='starmas',
            name='user',
            field=models.IntegerField(),
        ),
    ]
