# Generated by Django 5.2.8 on 2025-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_occupationmas_user_alter_starmas_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starmas',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manufacturemas',
            name='user',
        ),
        migrations.AddField(
            model_name='agentmas',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturemas',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commoditycodemas',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customermas',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suppliermas',
            name='user',
            field=models.IntegerField(),
        ),
    ]
