# Generated by Django 5.2.8 on 2025-11-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_rename_user_starmas_user_id_remove_agentmas_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationmas',
            old_name='user',
            new_name='user_id',
        ),
    ]
