# Generated by Django 5.2.8 on 2025-11-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_rename_user_occupationmas_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationmas',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
