# Generated by Django 5.2.8 on 2025-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_occupationmas_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmas',
            name='AlterdDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
