# Generated by Django 5.2.8 on 2025-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_bankmas_alterddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmas',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
