# Generated by Django 5.2.8 on 2025-12-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_agentmas_mobile_alter_agentmas_phoneno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemcategorymass1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Itemcategorymass9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountHeadMas',
        ),
        migrations.DeleteModel(
            name='BanksMas',
        ),
        migrations.DeleteModel(
            name='CompanyMas',
        ),
        migrations.DeleteModel(
            name='CourierTypeMas',
        ),
        migrations.DeleteModel(
            name='CustomerMas',
        ),
        migrations.DeleteModel(
            name='DocumentTypeMas',
        ),
        migrations.DeleteModel(
            name='ItemMas',
        ),
        migrations.DeleteModel(
            name='JobWorkChargeHeadMas',
        ),
        migrations.DeleteModel(
            name='ManufactureMas',
        ),
        migrations.DeleteModel(
            name='Naration',
        ),
        migrations.DeleteModel(
            name='ProductMas',
        ),
        migrations.DeleteModel(
            name='ProductRolMas',
        ),
        migrations.DeleteModel(
            name='PurchaseTypeMas',
        ),
        migrations.DeleteModel(
            name='TailorMas',
        ),
        migrations.DeleteModel(
            name='TransactionHead',
        ),
        migrations.DeleteModel(
            name='TransportMas',
        ),
        migrations.DeleteModel(
            name='UomMas',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='acc_head_name',
            new_name='AccHeadName',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='user_id',
            new_name='AccountHeadCode',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='account_no',
            new_name='AccountNo',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='area_code',
            new_name='AreaCode',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='cheque_name',
            new_name='ChequeName',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='commission_percent',
            new_name='CommissionPercent',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='cst_date',
            new_name='CstDate',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='cst_no',
            new_name='CstNo',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='fax',
            new_name='Fax',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='ifpn_no',
            new_name='IFPNNo',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='micr_code',
            new_name='MICRCode',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='panno',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='service_tax_no',
            new_name='Panno',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='tanno',
            new_name='Phoneno',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='tinno',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='website',
            new_name='ServiceTaxno',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='short_name',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='agentmas',
            old_name='tin_date',
            new_name='TinDate',
        ),
        migrations.RenameField(
            model_name='bankmas',
            old_name='Shortname',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='bankmas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='categorymas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='citymas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='commoditycodemas',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='commoditycodemas',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='countrymas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='departmentmas',
            old_name='Shortname',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='departmentmas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='employeemas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='floormas',
            old_name='Shortname',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='floormas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='grademas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='groupmas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='incomeandexpensemas',
            old_name='Shortname',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='occupationmas',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='occupationmas',
            old_name='short_name',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='relationmas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='religionmas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='starmas',
            old_name='starname',
            new_name='Starname',
        ),
        migrations.RenameField(
            model_name='starmas',
            old_name='starvalue',
            new_name='Starvalue',
        ),
        migrations.RenameField(
            model_name='statemas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='acc_head_name',
            new_name='AccHeadName',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='account_no',
            new_name='AccountNo',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='agent_commission',
            new_name='AgentCommission',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='area_code',
            new_name='AreaCode',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='account_head_code',
            new_name='BankCode',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='bill_discount',
            new_name='BillDiscount',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='agent_code',
            new_name='CashDiscountDays',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='cash_discount_percent',
            new_name='CashDiscountPercent',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='cheque_name',
            new_name='ChequeName',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='credit_limit',
            new_name='CreditLimit',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='cst_date',
            new_name='CstDate',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='cst_no',
            new_name='CstNo',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='dd_commission_percent',
            new_name='DDCommissionPercent',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='fax',
            new_name='Fax',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='gst_no',
            new_name='GSTNO',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='ifpn_no',
            new_name='IFPNNo',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='interest_on_delay',
            new_name='InterestonDelay',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='interest_on_early',
            new_name='InterestonEarly',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='micr_code',
            new_name='MICRCode',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='manual_cash_days',
            new_name='ManualCashDays',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='manual_cash_disc_per',
            new_name='ManualCashDiscPer',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='panno',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='print_name',
            new_name='Panno',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='tanno',
            new_name='Phoneno',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='tin_no',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='website',
            new_name='PrintName',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='profit',
            new_name='Profit',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='short_name',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='standard_discount_on_bill',
            new_name='StandardDiscountOnBill',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='tin_date',
            new_name='TinDate',
        ),
        migrations.RenameField(
            model_name='suppliermas',
            old_name='bank_code',
            new_name='TitleCode',
        ),
        migrations.RenameField(
            model_name='titlemas',
            old_name='Active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='account_head_code',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='code',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='ecs_transfer',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='agentmas',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='commoditycodemas',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='commoditycodemas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='countergroupmas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='countermas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='discounttypemas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='giftvouchermas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='incomeandexpensemas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='locationmas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='occupationmas',
            name='code',
        ),
        migrations.RemoveField(
            model_name='occupationmas',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='occupationmas',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='paymentmodemas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='starmas',
            name='code',
        ),
        migrations.RemoveField(
            model_name='starmas',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='starmas',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='cash_discount_days',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='company_depend',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='credit_days',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='debit_dd_commission',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='due_days',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='ecs_transfer',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='grade_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='representative_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='ss_account_head_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='title_code',
        ),
        migrations.RemoveField(
            model_name='suppliermas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemmas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='taxtypemas',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='transfermodemas',
            name='Active',
        ),
        migrations.AddField(
            model_name='agentmas',
            name='BankCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='CityCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='ECSTransfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='Tanno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='Tinno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='Website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commoditycodemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commoditycodemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupationmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='occupationmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='starmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='AccountHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='AgentCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='CategoryCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='CityCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='CompanyDepend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='CreditDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='DUEDAYS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='DebitDDCommission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='ECSTransfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='GradeCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='GroupCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='RepresendativeCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='SSAccHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='Tanno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='TinNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='Website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankmas',
            name='AlterdDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bankmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='categorymas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categorymas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citymas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='citymas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citymas',
            name='StateCode',
            field=models.ForeignKey(db_column='StateCode', on_delete=django.db.models.deletion.CASCADE, to='shop.statemas'),
        ),
        migrations.AlterField(
            model_name='citymas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countergroupmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='countergroupmas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countergroupmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='CounterGroupCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='CounterOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='SectionCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countermas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrymas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='countrymas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='countrymas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departmentmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discounttypemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discounttypemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='ChangeEmpRights',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='CommissionPercent',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='DayBasedIncentiveAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='DescEdit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='IncentiveQtyBased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='MaxAdvance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='Mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='NoofSystems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='OldBillCancel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='Phoneno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='Pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='ProfitFromCost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='SalesLessCostInPur',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='SalesLessCostInSales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='SalesManIncentive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='SystemRestrict',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='TargetAmount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floormas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='floormas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floormas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftvouchermas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giftvouchermas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grademas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grademas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grademas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupmas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groupmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomeandexpensemas',
            name='AccountPost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incomeandexpensemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incomeandexpensemas',
            name='HeadType',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incomeandexpensemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='CityCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='MainServer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='Mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='Phoneno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='Pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='UploadData',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentmodemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='relationmas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relationmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='religionmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='religionmas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='religionmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statemas',
            name='CountryCode',
            field=models.ForeignKey(db_column='CountryCode', on_delete=django.db.models.deletion.CASCADE, to='shop.countrymas'),
        ),
        migrations.AlterField(
            model_name='statemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statemas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='statemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemcountermas',
            name='CounterCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemcountermas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemcountermas',
            name='UserEntryDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemcountermas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='AllowScheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='FloorCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='LastNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='LocationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='NoLength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='PRINTERPORTCODE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='PrintFunctionCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='ReturnSystem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='SettlementPrintFunctionCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AccountHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AccountPost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AccountSalesHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AllowPurchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AllowSales',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='AllowTaxAmtCal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='Include',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='SSPurAccHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='SSSalAccHeadCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='TaxAmtCalType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='TaxOn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='TaxPercent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypemas',
            name='isDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='titlemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='titlemas',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='titlemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfermodemas',
            name='CreatedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfermodemas',
            name='NumGeneration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfermodemas',
            name='UserID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='agentmas',
            table='AgentMas',
        ),
        migrations.AlterModelTable(
            name='countergroupmas',
            table='CounterGroupMas',
        ),
        migrations.AlterModelTable(
            name='countermas',
            table='CounterMas',
        ),
        migrations.AlterModelTable(
            name='departmentmas',
            table='DepartmentMas',
        ),
        migrations.AlterModelTable(
            name='discounttypemas',
            table='DiscountTypeMas',
        ),
        migrations.AlterModelTable(
            name='giftvouchermas',
            table='GiftvoucherMas',
        ),
        migrations.AlterModelTable(
            name='incomeandexpensemas',
            table='IncomeAndExpenseMas',
        ),
        migrations.AlterModelTable(
            name='occupationmas',
            table='OccupationMas',
        ),
        migrations.AlterModelTable(
            name='paymentmodemas',
            table='PaymentModeMas',
        ),
        migrations.AlterModelTable(
            name='suppliermas',
            table='SupplierMas',
        ),
        migrations.AlterModelTable(
            name='systemcountermas',
            table='SystemCounterMas',
        ),
        migrations.AlterModelTable(
            name='systemmas',
            table='SystemMas',
        ),
        migrations.AlterModelTable(
            name='taxtypemas',
            table='TaxTypeMas',
        ),
        migrations.AlterModelTable(
            name='transfermodemas',
            table='TransferModeMas',
        ),
        migrations.AddField(
            model_name='agentmas',
            name='Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='agentmas',
            name='Sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countergroupmas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countermas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discounttypemas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giftvouchermas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incomeandexpensemas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationmas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occupationmas',
            name='Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paymentmodemas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='starmas',
            name='Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='suppliermas',
            name='Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='systemmas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxtypemas',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transfermodemas',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
